#! /bin/bash
#
focused_window_id=$(xdotool getwindowfocus)
windowInformations=$(xwininfo -id $focused_window_id)
width_and_height=$(echo $windowInformations| grep -P --only-matching 'geometry\s.*' | grep -P --only-matching '\d+x\d+' )
x_y_coordinates=$(xwininfo -id 121634830 | grep --only-matching -P 'Corners:\s+\+\d+\+\d+' | grep --only-matching -P '\+\d+\+\d+' )
echo $width_and_height$x_y_coordinates

