#! /bin/bash

SOCKET_FILE="/tmp/mpvsocket"

echo '{"command": ["set_property", "pause", true]}' | socat - $SOCKET_FILE

/opt/flameshot2/build/src/flameshot gui --region 1920x1080+0+0 --path /tmp/obsidianImages
