#!/bin/bash


 # awk -F '\t\t\t' 'NF >  0 {print $2}' ~/.config/mpv/mpv_history.log | grep -v '^$' |  awk -F '/home/' '{print "/home/"$NF}'| rofi -dmenu -i -p "Select a file" | parallel mpv {}
 awk -F '\t\t\t' 'NF >  0 {print $2}' ~/.config/mpv/mpv_history.log | grep -v '^$' |  awk -F '/home/' '{print "/home/"$NF}'| awk '!seen[$0]++' | rofi -dmenu -i -p "Select a file" | parallel mpv {}




