#! /bin/bash
set -e

SOCKET='/tmp/mpvsocket'

echo '{ "command": ["set_property", "pause", true] }' | socat - "${SOCKET}"
~/scripts/sub.py
~/flameshot/build/src/flameshot gui --region $(getCurrentlyActiveWindowCoordinates) --path /tmp/obsidianImages
