#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(find ~/work/builds ~/projects ~/ ~/work ~/personal ~/personal/yt -mindepth 1 -maxdepth 1 -type d | fzf)
    selected=$(zoxide query -l | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

#selected_name=$(basename "$selected" | tr . _)
#tmux_running=$(pgrep tmux)

clean_path=${selected%/}
# Use awk to split by '/' and take the last 3 elements
selected_name=$(echo "$clean_path" | awk -F'/' '{
    if (NF >= 3) {
        print $(NF-2)"_"$(NF-1)"_"$NF
    } else if (NF == 2) {
        print $(NF-1)"_"$NF
    } else {
        print $NF
    }
}' | tr . _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
