#!/bin/bash

find . -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.avi" \) -exec ffprobe -v quiet -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 {} \; | awk '{ sum += $1 } END { printf "Total duration: %d:%02d:%02d\n", sum/3600, (sum/60)%60, sum%60 }'
